version: '3.3'
services:
        elasticsearch:
                image: elasticsearch:7.4.0
                container_name: elasticsearch
                environment:
                        - cluster.name=docker-es-cluster
                        - node.name=elasticsearch
                        - bootstrap.memory_lock=true
                        - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
                        - cluster.initial_master_nodes=elasticsearch,elasticsearch2
                        - discovery.seed_hosts=elasticsearch,elasticsearch2
                ulimits:
                        memlock:
                                soft: -1
                                hard: -1
                volumes:
                        - esdata1:/Users/cwakshay/esdata
                ports:
                        - 19200:9200
                networks:
                        - esnet
        elasticsearch2:
                image: elasticsearch:7.4.0
                container_name: elasticsearch2
                environment:
                        - cluster.name=docker-es-cluster
                        - node.name=elasticsearch2
                        - bootstrap.memory_lock=true
                        - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
                        - cluster.initial_master_nodes=elasticsearch,elasticsearch2
                        - discovery.seed_hosts=elasticsearch,elasticsearch2
                ulimits:
                        memlock:
                                soft: -1
                                hard: -1
                ports:
                        - 29200:9200
                volumes:
                        - esdata2:/Users/cwakshay/esdata
                networks:
                        - esnet
        kibana:
                image: kibana:7.4.0
                container_name: kibana
                environment:
                        ELASTICSEARCH_HOSTS: http://elasticsearch2:9200
                ports:
                        - 15601:5601
                networks:
                        - esnet
volumes:
        esdata1:
                driver: local
        esdata2:
                driver: local


networks:
        esnet:
